// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL1BUWQHPjbt8feN81ZvTbW8vRZlj-I1o',
    appId: '1:501794394203:web:8bf1f9b6cdd117abbaaf7e',
    messagingSenderId: '501794394203',
    projectId: 'project-a9d9f',
    authDomain: 'project-a9d9f.firebaseapp.com',
    storageBucket: 'project-a9d9f.appspot.com',
    measurementId: 'G-4Z69GYYHDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKfu8RPtLHmINzIMG3-IvdVmpLaaXWe0',
    appId: '1:501794394203:android:fd209d934804adf6baaf7e',
    messagingSenderId: '501794394203',
    projectId: 'project-a9d9f',
    storageBucket: 'project-a9d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmKB1HmFpee3npwPelf5H0dLoqvMLUpBw',
    appId: '1:501794394203:ios:9625cc9ad2104091baaf7e',
    messagingSenderId: '501794394203',
    projectId: 'project-a9d9f',
    storageBucket: 'project-a9d9f.appspot.com',
    iosClientId: '501794394203-1qir1g02r4rbuu8l65ssioa951942gfu.apps.googleusercontent.com',
    iosBundleId: 'com.goggxi.firebasePagination',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmKB1HmFpee3npwPelf5H0dLoqvMLUpBw',
    appId: '1:501794394203:ios:9625cc9ad2104091baaf7e',
    messagingSenderId: '501794394203',
    projectId: 'project-a9d9f',
    storageBucket: 'project-a9d9f.appspot.com',
    iosClientId: '501794394203-1qir1g02r4rbuu8l65ssioa951942gfu.apps.googleusercontent.com',
    iosBundleId: 'com.goggxi.firebasePagination',
  );
}
